<a href="https://colab.research.google.com/github/arshad62/5_days_AI_Agents_Training/blob/main/03_Image_Sound_RAG_Ollama_fastapi/03_voice_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -Uq tensorflow_hub  pydub

In [2]:
!pip install -Uq tensorflow-io

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 MB 11.2 MB/s eta 0:00:00


In [4]:
import tensorflow as tf
import tensorflow_hub as hub

# Load the YAMNET model
model = hub.load('https://tfhub.dev/google/yamnet/1')

# Load an audio file
audio, sample_rate = tf.audio.decode_wav(tf.io.read_file('audio/h1.wav'))
audio = tf.squeeze(audio, axis=-1)

# Generate embeddings
scores, embeddings, log_mel_spectrogram = model(audio)

print(f"Audio embedding shape: {embeddings.shape}")

Audio embedding shape: (34, 1024)


In [5]:
# Load an audio file
audio, sample_rate = tf.audio.decode_wav(tf.io.read_file('audio/a2.wav'))
audio = tf.squeeze(audio, axis=-1)

scores, embeddings, log_mel_spectrogram = model(audio)

print(f"Audio embedding shape: {embeddings.shape}")#27,18

Audio embedding shape: (41, 1024)


In [6]:
log_mel_spectrogram

<tf.Tensor: shape=(2016, 64), dtype=float32, numpy=
array([[-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554],
       [-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554],
       [-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554],
       ...,
       [-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554],
       [-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554],
       [-6.9077554, -6.9077554, -6.9077554, ..., -6.9077554, -6.9077554,
        -6.9077554]], dtype=float32)>

#  we found shape dimension error
* you can solve with slicing

In [7]:
import os
import numpy as np

voices = []
labels = []
for i in os.listdir("./audio/"):
    if '.wav' in i:
        name = i.split(".")[0]


        audio, sample_rate = tf.audio.decode_wav(tf.io.read_file(f'./audio/{i}'))
        audio = tf.squeeze(audio, axis=-1)

        scores, embeddings, log_mel_spectrogram = model(audio)

        voices.append(np.array(embeddings[:5,:]).ravel())
        labels.append(name)

        print(f"Audio embedding shape: {embeddings.shape} new shape {embeddings[:5,:].shape} type {type(np.array(embeddings[:18,:]))}")#27,18
        print(i)

Audio embedding shape: (27, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
q1.wav
Audio embedding shape: (18, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
q2.wav
Audio embedding shape: (42, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
h2.wav
Audio embedding shape: (41, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
a2.wav
Audio embedding shape: (34, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
h1.wav
Audio embedding shape: (29, 1024) new shape (5, 1024) type <class 'numpy.ndarray'>
a1.wav


In [8]:
voices

[array([2.3242722 , 0.17074096, 0.2154259 , ..., 0.01817111, 1.7490286 ,
        1.8252875 ], dtype=float32),
 array([2.1035516 , 0.28917378, 0.6604178 , ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([1.8627609 , 0.10154393, 0.7127788 , ..., 0.2883883 , 1.3826836 ,
        2.7965813 ], dtype=float32),
 array([1.6946357 , 0.36075842, 0.6930005 , ..., 0.9783656 , 0.12747978,
        0.        ], dtype=float32),
 array([2.2192943 , 0.14239843, 0.6774469 , ..., 0.        , 0.        ,
        0.        ], dtype=float32),
 array([0.        , 0.25089622, 0.09453693, ..., 0.        , 0.        ,
        0.        ], dtype=float32)]

In [10]:
!pip install pymilvus

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 78.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 MB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 4.8 MB/s eta 0:00:00
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.69.0
    Uninstalling grpcio-1.69.0:
      Successfully uninstalled grpcio-1.69.0


In [12]:
!pip install grpcio<=1.67.1,>=1.49.1


/bin/bash: line 1: =1.67.1,: No such file or directory


In [14]:
!python3 -m venv .venv
!source .venv/bin/activate
!pip install pymilvus

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /content/.venv/bin/python3

/bin/bash: line 1: .venv/bin/activate: No such file or directory


In [15]:
!source .venv/bin/activate
!pip uninstall pymilvus
!pip install pymilvus

/bin/bash: line 1: .venv/bin/activate: No such file or directory
Found existing installation: pymilvus 2.5.3
Uninstalling pymilvus-2.5.3:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/pymilvus-2.5.3.dist-info/*
    /usr/local/lib/python3.10/dist-packages/pymilvus/*
Proceed (Y/n)? Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/uninstall.py", line 106, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_install.py", line 722, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/req/req_uninstall.py", line 364, in remove
    if auto_confirm or self._allowed_to_proceed(verbose):
  File "/usr/local/lib/python3.10/dist-packages/pip/_intern

In [18]:
#Imports a PyMilvus package:
from pymilvus import (
    connections,
    utility,
    FieldSchema,
    CollectionSchema,
    DataType,
    Collection,
)

#Connect to the Milvus
connections.connect("default", host="localhost", port="19530")
# Define the collection name
collection_name = "audio"

# Delete old collection if it exists
if utility.has_collection(collection_name):
    Collection(collection_name).drop()


#Creates a collection:
fields = [
    FieldSchema(name="pk", dtype=DataType.INT64, is_primary=True, auto_id=False),
    FieldSchema(name="words", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="person_name", dtype=DataType.VARCHAR, max_length=50),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=5120)
]
schema = CollectionSchema(fields, "Simple Demo for audio similar search")
audio = Collection("audio", schema)


ContextualVersionConflict: (grpcio 1.69.0 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('grpcio<=1.67.1,>=1.49.1'), {'pymilvus'})

In [17]:
!python3 -m venv .venv
!source .venv/bin/activate
!pip install pymilvus

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /content/.venv/bin/python3

/bin/bash: line 1: .venv/bin/activate: No such file or directory


In [ ]:
# Builds indexes on the entities:

index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

audio.create_index("embeddings", index)

Status(code=0, message=)

In [ ]:
labels

['a2', 'a1', 'h1', 'q2', 'h2', 'q1']

In [ ]:
voices[0].shape

(5120,)

In [ ]:
#Insert data in collection
data = [
    [1,2,3,4,5,6],  # field pk
    labels,  # field words
    ["Auranzaib","Auranzaib","Hasnant","Qasim","Hasnant","Qasim"],
    voices,  # field embeddings
]

In [ ]:
audio.insert(data)
audio.flush()
audio.load()

In [ ]:
search_params = {"metric_type": "L2"}

In [ ]:
results = audio.search(
	data=[voices[0]],
	anns_field="embeddings",
	param=search_params,
	limit=4,
	expr=None,
	# set the names of the fields you want to retrieve from the search result.
	output_fields=['words','person_name'],
	consistency_level="Strong"
)

In [ ]:
for i in range(0,len(results[0])):
    name = results[0][i].entity.get('words')
    pname = results[0][i].entity.get('person_name')
    print(pname)
#     try:
#         display(Image.open('./images/'+name+'.jpg'))
#     except:
#         display(Image.open('./images/'+name+'.png'))

Auranzaib
Auranzaib
Qasim
Hasnant


In [ ]:
labels

['a2', 'a1', 'h1', 'q2', 'h2', 'q1']